import {
  AuditRuleCategory,
  AuditRuleSeverity,
  type AuditRuleCategory as AuditRuleCategoryType,
  type AuditRuleSeverity as AuditRuleSeverityType,
} from "../rules-types";

/** Metadata for a rule outcome (fail/warn/pass variants). */
export type RuleOutcomeConfig = {
  code: string;
  category: AuditRuleCategoryType;
  severity: AuditRuleSeverityType;
  scoreImpact: number;
  previewVisible: boolean;
  estimatedFixMinutes: number;
};

/** Central registry of rule codes and scoring metadata. */
export const RuleConfig = {
  HTTPS_PASS: {
    code: "https_enabled",
    category: AuditRuleCategory.SECURITY,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  HTTPS_MISSING: {
    code: "https_missing",
    category: AuditRuleCategory.SECURITY,
    severity: AuditRuleSeverity.CRITICAL,
    scoreImpact: 11,
    previewVisible: true,
    estimatedFixMinutes: 30,
  },
  STATUS_CODE_OK: {
    code: "status_code_ok",
    category: AuditRuleCategory.TECHNICAL,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  STATUS_CODE_ERROR: {
    code: "status_code_error",
    category: AuditRuleCategory.TECHNICAL,
    severity: AuditRuleSeverity.HIGH,
    scoreImpact: 8,
    previewVisible: false,
    estimatedFixMinutes: 45,
  },
  TITLE_PRESENT: {
    code: "title_present",
    category: AuditRuleCategory.CONTENT,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  TITLE_MISSING: {
    code: "title_missing",
    category: AuditRuleCategory.CONTENT,
    severity: AuditRuleSeverity.CRITICAL,
    scoreImpact: 12,
    previewVisible: true,
    estimatedFixMinutes: 5,
  },
  TITLE_LENGTH_NA: {
    code: "title_length_na",
    category: AuditRuleCategory.CONTENT,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  TITLE_LENGTH_OK: {
    code: "title_length_ok",
    category: AuditRuleCategory.CONTENT,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  TITLE_TOO_SHORT: {
    code: "title_too_short",
    category: AuditRuleCategory.CONTENT,
    severity: AuditRuleSeverity.MEDIUM,
    scoreImpact: 4,
    previewVisible: false,
    estimatedFixMinutes: 5,
  },
  TITLE_TOO_LONG: {
    code: "title_too_long",
    category: AuditRuleCategory.CONTENT,
    severity: AuditRuleSeverity.MEDIUM,
    scoreImpact: 4,
    previewVisible: false,
    estimatedFixMinutes: 5,
  },
  META_DESCRIPTION_PRESENT: {
    code: "meta_description_present",
    category: AuditRuleCategory.CONTENT,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  META_DESCRIPTION_MISSING: {
    code: "meta_description_missing",
    category: AuditRuleCategory.CONTENT,
    severity: AuditRuleSeverity.HIGH,
    scoreImpact: 9,
    previewVisible: true,
    estimatedFixMinutes: 5,
  },
  META_DESCRIPTION_LENGTH_NA: {
    code: "meta_description_length_na",
    category: AuditRuleCategory.CONTENT,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  META_DESCRIPTION_LENGTH_OK: {
    code: "meta_description_length_ok",
    category: AuditRuleCategory.CONTENT,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  META_DESCRIPTION_TOO_SHORT: {
    code: "meta_description_too_short",
    category: AuditRuleCategory.CONTENT,
    severity: AuditRuleSeverity.MEDIUM,
    scoreImpact: 3,
    previewVisible: false,
    estimatedFixMinutes: 5,
  },
  META_DESCRIPTION_TOO_LONG: {
    code: "meta_description_too_long",
    category: AuditRuleCategory.CONTENT,
    severity: AuditRuleSeverity.MEDIUM,
    scoreImpact: 3,
    previewVisible: false,
    estimatedFixMinutes: 5,
  },
  H1_SINGLE: {
    code: "h1_single",
    category: AuditRuleCategory.CONTENT,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  H1_MISSING: {
    code: "h1_missing",
    category: AuditRuleCategory.CONTENT,
    severity: AuditRuleSeverity.HIGH,
    scoreImpact: 8,
    previewVisible: true,
    estimatedFixMinutes: 10,
  },
  H1_MULTIPLE: {
    code: "h1_multiple",
    category: AuditRuleCategory.CONTENT,
    severity: AuditRuleSeverity.MEDIUM,
    scoreImpact: 5,
    previewVisible: true,
    estimatedFixMinutes: 15,
  },
  CANONICAL_PRESENT: {
    code: "canonical_present",
    category: AuditRuleCategory.TECHNICAL,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  CANONICAL_MISSING: {
    code: "canonical_missing",
    category: AuditRuleCategory.TECHNICAL,
    severity: AuditRuleSeverity.MEDIUM,
    scoreImpact: 4,
    previewVisible: false,
    estimatedFixMinutes: 10,
  },
  ROBOTS_INDEXABLE: {
    code: "robots_indexable",
    category: AuditRuleCategory.TECHNICAL,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  ROBOTS_NOINDEX: {
    code: "robots_noindex",
    category: AuditRuleCategory.TECHNICAL,
    severity: AuditRuleSeverity.CRITICAL,
    scoreImpact: 12,
    previewVisible: true,
    estimatedFixMinutes: 5,
  },
  VIEWPORT_PRESENT: {
    code: "viewport_present",
    category: AuditRuleCategory.ACCESSIBILITY,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  VIEWPORT_MISSING: {
    code: "viewport_missing",
    category: AuditRuleCategory.ACCESSIBILITY,
    severity: AuditRuleSeverity.HIGH,
    scoreImpact: 9,
    previewVisible: true,
    estimatedFixMinutes: 3,
  },
  HTML_LANG_PRESENT: {
    code: "html_lang_present",
    category: AuditRuleCategory.ACCESSIBILITY,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  HTML_LANG_MISSING: {
    code: "html_lang_missing",
    category: AuditRuleCategory.ACCESSIBILITY,
    severity: AuditRuleSeverity.LOW,
    scoreImpact: 2,
    previewVisible: false,
    estimatedFixMinutes: 3,
  },
  OPEN_GRAPH_PRESENT: {
    code: "open_graph_present",
    category: AuditRuleCategory.SOCIAL,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  OPEN_GRAPH_MISSING: {
    code: "open_graph_missing",
    category: AuditRuleCategory.SOCIAL,
    severity: AuditRuleSeverity.LOW,
    scoreImpact: 2,
    previewVisible: false,
    estimatedFixMinutes: 15,
  },
  TWITTER_CARD_PRESENT: {
    code: "twitter_card_present",
    category: AuditRuleCategory.SOCIAL,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  TWITTER_CARD_MISSING: {
    code: "twitter_card_missing",
    category: AuditRuleCategory.SOCIAL,
    severity: AuditRuleSeverity.LOW,
    scoreImpact: 1,
    previewVisible: false,
    estimatedFixMinutes: 10,
  },
  IMAGES_NONE: {
    code: "images_none",
    category: AuditRuleCategory.ACCESSIBILITY,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  IMAGE_ALT_GOOD: {
    code: "image_alt_good",
    category: AuditRuleCategory.ACCESSIBILITY,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  IMAGE_ALT_WEAK: {
    code: "image_alt_weak",
    category: AuditRuleCategory.ACCESSIBILITY,
    severity: AuditRuleSeverity.MEDIUM,
    scoreImpact: 4,
    previewVisible: false,
    estimatedFixMinutes: 20,
  },
  INTERNAL_LINKS_OK: {
    code: "internal_links_ok",
    category: AuditRuleCategory.TECHNICAL,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  INTERNAL_LINKS_LOW: {
    code: "internal_links_low",
    category: AuditRuleCategory.TECHNICAL,
    severity: AuditRuleSeverity.MEDIUM,
    scoreImpact: 3,
    previewVisible: false,
    estimatedFixMinutes: 20,
  },
  SCHEMA_PRESENT: {
    code: "schema_present",
    category: AuditRuleCategory.AI_READINESS,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  SCHEMA_MISSING: {
    code: "schema_missing",
    category: AuditRuleCategory.AI_READINESS,
    severity: AuditRuleSeverity.MEDIUM,
    scoreImpact: 5,
    previewVisible: false,
    estimatedFixMinutes: 20,
  },
  FAQ_SCHEMA_PRESENT: {
    code: "faq_schema_present",
    category: AuditRuleCategory.AI_READINESS,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  FAQ_SCHEMA_MISSING: {
    code: "faq_schema_missing",
    category: AuditRuleCategory.AI_READINESS,
    severity: AuditRuleSeverity.MEDIUM,
    scoreImpact: 4,
    previewVisible: false,
    estimatedFixMinutes: 30,
  },
  BUSINESS_SCHEMA_PRESENT: {
    code: "business_schema_present",
    category: AuditRuleCategory.LOCAL_SEO,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  BUSINESS_SCHEMA_MISSING: {
    code: "business_schema_missing",
    category: AuditRuleCategory.LOCAL_SEO,
    severity: AuditRuleSeverity.MEDIUM,
    scoreImpact: 5,
    previewVisible: false,
    estimatedFixMinutes: 25,
  },
  WORD_COUNT_OK: {
    code: "word_count_ok",
    category: AuditRuleCategory.CONTENT,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  WORD_COUNT_LOW: {
    code: "word_count_low",
    category: AuditRuleCategory.CONTENT,
    severity: AuditRuleSeverity.MEDIUM,
    scoreImpact: 5,
    previewVisible: true,
    estimatedFixMinutes: 60,
  },
  WORD_COUNT_VERY_LOW: {
    code: "word_count_low",
    category: AuditRuleCategory.CONTENT,
    severity: AuditRuleSeverity.HIGH,
    scoreImpact: 8,
    previewVisible: true,
    estimatedFixMinutes: 60,
  },
  RESPONSE_TIME_OK: {
    code: "response_time_ok",
    category: AuditRuleCategory.PERFORMANCE,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
  RESPONSE_TIME_SLOW: {
    code: "response_time_slow",
    category: AuditRuleCategory.PERFORMANCE,
    severity: AuditRuleSeverity.MEDIUM,
    scoreImpact: 5,
    previewVisible: true,
    estimatedFixMinutes: 90,
  },
  RESPONSE_TIME_CRITICAL: {
    code: "response_time_critical",
    category: AuditRuleCategory.PERFORMANCE,
    severity: AuditRuleSeverity.HIGH,
    scoreImpact: 9,
    previewVisible: true,
    estimatedFixMinutes: 90,
  },
  RULE_EXECUTION_FAILED: {
    code: "RULE_EXECUTION_FAILED",
    category: AuditRuleCategory.OTHER,
    severity: AuditRuleSeverity.INFO,
    scoreImpact: 0,
    previewVisible: false,
    estimatedFixMinutes: 0,
  },
} as const satisfies Record<string, RuleOutcomeConfig>;

export type RuleConfigKey = keyof typeof RuleConfig;
